log-level = "info"
log-file = ""

[server]
addr = "127.0.0.1:20160"
advertise-addr = ""
notify-capacity = 40960
messages-per-tick = 4096
grpc-concurrency = 4
grpc-concurrent-stream = 1024
grpc-raft-conn-num = 10
grpc-stream-initial-window-size = "2MB"
end-point-concurrency = 4
end-point-max-tasks = 2000

[server.labels]

[storage]
data-dir = ""
gc-ratio-threshold = 1.1
scheduler-notify-capacity = 10240
scheduler-messages-per-tick = 1024
scheduler-concurrency = 102400
scheduler-worker-pool-size = 4
scheduler-too-busy-threshold = 1000

[pd]
endpoints = []

[metric]
interval = "15s"
address = ""
job = "tikv"

[raftstore]
sync-log = true
raftdb-path = ""
capacity = "0KB"
raft-base-tick-interval = "1s"
raft-heartbeat-ticks = 2
raft-election-timeout-ticks = 10
raft-max-size-per-msg = "1MB"
raft-max-inflight-msgs = 256
raft-entry-max-size = "8MB"
raft-log-gc-tick-interval = "10s"
raft-log-gc-threshold = 50
raft-log-gc-count-limit = 196608
raft-log-gc-size-limit = "192MB"
split-region-check-tick-interval = "10s"
region-max-size = "10MB"
region-split-size = "1MB"
region-split-check-diff = "1MB"
region-compact-check-interval = "0s"
region-compact-delete-keys-count = 1000000
pd-heartbeat-tick-interval = "1m"
pd-store-heartbeat-tick-interval = "10s"
snap-mgr-gc-tick-interval = "1m"
snap-gc-timeout = "4h"
lock-cf-compact-interval = "10m"
lock-cf-compact-bytes-threshold = "256MB"
notify-capacity = 40960
messages-per-tick = 4096
max-peer-down-duration = "5m"
max-leader-missing-duration = "2h"
snap-apply-batch-size = "10MB"
consistency-check-interval = "0s"
report-region-flow-interval = "1m"
raft-store-max-leader-lease = "9s"
right-derive-when-split = true
allow-remove-leader = false

[rocksdb]
wal-recovery-mode = 2
wal-dir = ""
wal-ttl-seconds = 0
wal-size-limit = "0KB"
max-total-wal-size = "4GB"
max-background-jobs = 6
max-manifest-file-size = "20MB"
create-if-missing = true
max-open-files = 40960
enable-statistics = true
stats-dump-period = "10m"
compaction-readahead-size = "0KB"
info-log-max-size = "0KB"
info-log-roll-time = "0s"
info-log-dir = ""
rate-bytes-per-sec = "0KB"
max-sub-compactions = 1
writable-file-max-buffer-size = "1MB"
use-direct-io-for-flush-and-compaction = false
enable-pipelined-write = true
backup-dir = ""

[rocksdb.defaultcf]
block-size = "64KB"
block-cache-size = "4GB"
cache-index-and-filter-blocks = true
use-bloom-filter = true
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
compression-per-level = [
    "no",
    "no",
    "lz4",
    "lz4",
    "lz4",
    "zstd",
    "zstd",
]
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "512MB"
target-file-size-base = "8MB"
level0-file-num-compaction-trigger = 4
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 3

[rocksdb.writecf]
block-size = "64KB"
block-cache-size = "2457MB"
cache-index-and-filter-blocks = true
use-bloom-filter = true
whole-key-filtering = false
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
compression-per-level = [
    "no",
    "no",
    "lz4",
    "lz4",
    "lz4",
    "zstd",
    "zstd",
]
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "512MB"
target-file-size-base = "8MB"
level0-file-num-compaction-trigger = 4
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 3

[rocksdb.lockcf]
block-size = "16KB"
block-cache-size = "327MB"
cache-index-and-filter-blocks = true
use-bloom-filter = true
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
compression-per-level = [
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
]
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "128MB"
target-file-size-base = "8MB"
level0-file-num-compaction-trigger = 1
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 0

[rocksdb.raftcf]
block-size = "16KB"
block-cache-size = "128MB"
cache-index-and-filter-blocks = true
use-bloom-filter = true
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
compression-per-level = [
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
    "no",
]
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "128MB"
target-file-size-base = "8MB"
level0-file-num-compaction-trigger = 1
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 0

[raftdb]
wal-recovery-mode = 2
wal-dir = ""
wal-ttl-seconds = 0
wal-size-limit = "0KB"
max-total-wal-size = "4GB"
max-manifest-file-size = "20MB"
create-if-missing = true
max-open-files = 40960
enable-statistics = true
stats-dump-period = "10m"
compaction-readahead-size = "0KB"
info-log-max-size = "0KB"
info-log-roll-time = "0s"
info-log-dir = ""
max-sub-compactions = 1
writable-file-max-buffer-size = "1MB"
use-direct-io-for-flush-and-compaction = false
enable-pipelined-write = true
allow-concurrent-memtable-write = false

[raftdb.defaultcf]
block-size = "64KB"
block-cache-size = "327MB"
cache-index-and-filter-blocks = true
use-bloom-filter = false
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
compression-per-level = [
    "no",
    "no",
    "lz4",
    "lz4",
    "lz4",
    "zstd",
    "zstd",
]
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "512MB"
target-file-size-base = "8MB"
level0-file-num-compaction-trigger = 4
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 0

